"""Re-export shared fixtures from _fixtures.py so pytest can auto-inject them.

_fixtures.py also exposes plain helpers (e.g. write_reference_requirement) that
tests import directly by name, so it is kept as a regular module rather than a
conftest.py itself. Fixtures need to be visible here for pytest's fixture
discovery to find them without an explicit import in each test module.
"""

from __future__ import annotations

import sys

# Compiled packs have an exact, hash-verified file set: verify_compiled_pack
# rejects generated bytecode as an unexpected file. Tests import pack-copied
# modules (the runtime contract, the Isaac launcher) whose call-time imports
# would otherwise write __pycache__ into a shared pack fixture.
sys.dont_write_bytecode = True

from _fixtures import (  # noqa: E402
    compiled_electrodeposition_coverage_world,
    compiled_electrodeposition_world,
    failed_trace_events,
    three_station_composition,
    trace_with_complete_lineage,
    trace_with_forked_sample,
    trace_with_missing_transfer,
    trace_with_vanished_sample,
    truncated_trace_events,
    two_observer_composition,
)

__all__ = [
    "compiled_electrodeposition_coverage_world",
    "compiled_electrodeposition_world",
    "failed_trace_events",
    "three_station_composition",
    "trace_with_complete_lineage",
    "trace_with_forked_sample",
    "trace_with_missing_transfer",
    "trace_with_vanished_sample",
    "truncated_trace_events",
    "two_observer_composition",
]
